---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)

library(shiny)
library(shinyWidgets)
library(lubridate)
library(tidyverse)
library(modelr)
library(lubridate)
library(dplyr)
library(glmnet)
library(caret)
library(pROC)
library(caTools)
library(randomForest)
addResourcePath("img", "img")


flightPricePredict <- function(Airline, Source, Destination, Journey_day, Days_left, Class, Total_stops, Arrival, Departure){
  flight_new = read_csv("Flights Price Prediction Dataset/Cleaned_dataset.csv", show_col_types = FALSE)
  flight_new["Total_stops"][flight_new["Total_stops"]== "non-stop"] <- '0'
  flight_new["Total_stops"][flight_new["Total_stops"]== "1-stop"] <- '1'
  flight_new["Total_stops"][flight_new["Total_stops"]== "2+-stop"] <- '2'
  flight_new$Total_stops = as.numeric(flight_new$Total_stops)
  
  cat(Airline, Source, Destination, Journey_day, Days_left, Class, Total_stops, Arrival, Departure)
  
  model <- readRDS("model_file_Random_Forest.rds")
  #Journey_day = strftime(Flight_date,"%A")
  flight_inpt = data.frame(Journey_day, Airline, Class, Source, Departure, Total_stops, Arrival, Destination, Days_left)
  inp = model.matrix( ~ ., data =rbind(flight_inpt, select(flight_new,-Fare, -Flight_code, -Date_of_journey, -Duration_in_hours)))
  temp = predict(model, newdata=inp)
  prd = as.numeric(temp[1])
  
  for (i in Days_left:1) {
    flight_inpt = data.frame(Journey_day, Airline, Class, Source, Departure, Total_stops, Arrival, Destination, Days_left=i)
    inp = model.matrix( ~ ., data =rbind(flight_inpt, select(flight_new,-Fare, -Flight_code, -Date_of_journey, -Duration_in_hours)))
    temp_n = predict(model, newdata=inp)
    prd_n = as.numeric(temp_n[1])
    prd = append(prd, prd_n)
  }
  rtn = list(rev(prd[-1]), which.min(rev(prd[-1])))
  return(rtn)
}
```
Column {.sidebar}
-----------------------------------------------------------------------


```{r}
selectInput("depc", h3("Departure City"), 
                       choices = list("Hyderabad", "Bangalore",
                                      "Kolkata", "Chennai", 
                                      "Delhi", "Mumbai",
                                      "Ahmedabad"), selected = 1)
selectInput("arrc", h3("Arrival City"), 
                       choices = list("Hyderabad", "Bangalore",
                                                "Kolkata", "Chennai", 
                                                "Delhi", "Mumbai",
                                                "Ahmedabad"), selected = 1)
           selectInput("stops", h3("Number of Stops"), 
                       choices = list("Zero" = 0, "One" = 1, "Two" = 2
                                      ), selected = 0)
           selectInput("airline", h3("Airline"), 
                       choices = list("Air India", "Indigo",
                                      "SpiceJet", "Go FIRST", 
                                      "AirAsia", "Vistara", "AkasaAir", "StarAir", "AllianceAir"), selected = 1)
           
selectInput("seat_class", h3("Class"), 
                       choices = list("Economy","Premium Economy", "Business","First"
                                      ), selected = 1)
selectInput("deptime", h3("Departure Time"), 
                       choices = list("After 6 PM","Before 6 AM", "6 AM - 12 PM","12 PM - 6 PM"
                       ), selected = 1)
           selectInput("arrtime", h3("Arrival Time"), 
                       choices = list("After 6 PM","Before 6 AM", "6 AM - 12 PM","12 PM - 6 PM"
                       ), selected = 1)
dateInput("date", h3("Select Date"),
             min = as.Date(today()),
             max = NULL)
actionButton("submit","Submit")


    
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
Journey_day = strftime(date,"%A")
date_inp <- reactive((input$date))
    aaj <- as.Date(today())
    days_left <- as.numeric(difftime(((date_inp())),aaj))
    pred = flightPricePredict(airline, depc, arrc, Journey_day, days_left, seat_class, as.numeric(stops),   arrtime, deptime)

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
plot(diamonds$color, diamonds$x)
```

### Chart C

```{r}
plot(diamonds$depth, diamonds$clarity)
```

